name: metro-api
channels:
- conda-forge
dependencies:
- python=3.7.0
- pip
- pip:
  - --extra-index-url https://test.pypi.org/simple/
  - docker==5.0.3
  - sanic==21.12.1
  - aiofiles==0.8.0
  - metrograph==0.0.1.post1
  - redis==4.1.4
  - pickle5==0.0.12