name: metro-api
channels:
- conda-forge
dependencies:
- python=3.8.1
- pip
- pip:
  - --extra-index-url https://test.pypi.org/simple/
  - docker==5.0.3
  - sanic==22.3.1
  - aiofiles==0.8.0
  - metrograph==0.0.1.post1
  - redis==4.1.4
  - pickle5==0.0.11
  - Sphinx==4.4.0
  - pyjwt==2.3.0
  - bcrypt==3.2.0
  - schedule==1.1.0