name: metro-api
channels:
- conda-forge
dependencies:
- python=3.7.0
- pip
- pip:
  - --extra-index-url https://test.pypi.org/simple/
  - sanic==21.12.1
  - aiofiles==0.8.0
  - wheel==0.37.1
  - setuptools==60.9.3
  - twine==3.8.0
  - metrograph==0.0.1.post1