name: metro-api
channels:
- conda-forge
dependencies:
- python=3.8.1
- pip
- pip:
  - docker==5.0.3
  - sanic==22.3.1
  - aiofiles==0.8.0
  - metrograph==0.0.7
  - redis==4.1.4
  - pickle5==0.0.11
  - Sphinx==4.4.0
  - pyjwt==2.3.0
  - bcrypt==3.2.0
  - schedule==1.1.0
  - minio==7.1.8
  - urllib3==1.26.9
  - boto3==1.23.0 